/*
 * This file is generated by jOOQ.
 */
package com.dubhe.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;
    private Integer author;

    public Book() {}

    public Book(Book value) {
        this.id = value.id;
        this.name = value.name;
        this.author = value.author;
    }

    public Book(
        Integer id,
        String  name,
        Integer author
    ) {
        this.id = id;
        this.name = name;
        this.author = author;
    }

    /**
     * Getter for <code>jooq.book.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>jooq.book.id</code>.
     */
    public Book setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>jooq.book.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>jooq.book.name</code>.
     */
    public Book setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>jooq.book.author</code>.
     */
    public Integer getAuthor() {
        return this.author;
    }

    /**
     * Setter for <code>jooq.book.author</code>.
     */
    public Book setAuthor(Integer author) {
        this.author = author;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Book other = (Book) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (author == null) {
            if (other.author != null)
                return false;
        }
        else if (!author.equals(other.author))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.author == null) ? 0 : this.author.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(author);

        sb.append(")");
        return sb.toString();
    }
}
