/*
 * This file is generated by jOOQ.
 */
package com.dubhe.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customer implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;
    private Integer age;

    public Customer() {}

    public Customer(Customer value) {
        this.id = value.id;
        this.name = value.name;
        this.age = value.age;
    }

    public Customer(
        Integer id,
        String  name,
        Integer age
    ) {
        this.id = id;
        this.name = name;
        this.age = age;
    }

    /**
     * Getter for <code>jooq.customer.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>jooq.customer.id</code>.
     */
    public Customer setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>jooq.customer.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>jooq.customer.name</code>.
     */
    public Customer setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>jooq.customer.age</code>.
     */
    public Integer getAge() {
        return this.age;
    }

    /**
     * Setter for <code>jooq.customer.age</code>.
     */
    public Customer setAge(Integer age) {
        this.age = age;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Customer other = (Customer) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (age == null) {
            if (other.age != null)
                return false;
        }
        else if (!age.equals(other.age))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.age == null) ? 0 : this.age.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customer (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(age);

        sb.append(")");
        return sb.toString();
    }
}
