/*
 * This file is generated by jOOQ.
 */
package com.dubhe.jooq.model;


import com.dubhe.jooq.model.tables.Author;
import com.dubhe.jooq.model.tables.Book;


/**
 * Convenience access to all tables in jooq.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>jooq.book</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
