/*
 * This file is generated by jOOQ.
 */
package com.dubhe.jooq.model;


import com.dubhe.jooq.model.tables.Book;
import com.dubhe.jooq.model.tables.Customer;

/**
 * Convenience access to all tables in jooq.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>jooq.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;
}
